### ISSUE TITLE
Seletores e Conteúdo geral

### ISSUE THREAD

**Issue by VitorGultzgoff** [mathh95/css4noobs#15]
- Está faltando os seletores **Pseudo-elements** e **Attribute Selector**.
- Apesar de ser um guia voltado para **iniciantes**, creio que a _linguagem_ que será utilizada, deverá ser _universal e direcionada_. Exemplo: Ao invés de aplicar a seguinte **descrição**:

> Seletor simplesmente é você informar quais elementos se aplicam a uma regra (estilo) definida por você, devemos ficar atento pois o seletor pega todos os elementos que ele encontra.

**reescrever** da seguinte maneira:

> Seletores são padrões utilizados para selecionar elementos no DOM, através de regras e filtros que variam desde à definição do(s) próprio(s) elemento(s), bem como o estado em que se encontra(m).

- O modo como foi abordado a aplicação do estilo nos elementos, mesmo que sejam exemplos, está trazendo **más práticas de HTML**, o que pode acabar resultando em um vício futuro não controlado, **elementos genéricos são tradados como 'div'**, exemplo:

> todos elementos div com a class vermelho.

- Creio que também podemos elaborar alguns **exemplos mais práticos**, com **aplicações reais** (mesmo que seja um protótipo), para **facilitar no entendimento**.

O que vocês acham ? Posso _ajudar_ na aplicação dos comentários acima ?

**Comment by mathh95** [comment]
fique a vontade vitor, todo o feedback e ajuda são bem vindos.
