### ISSUE TITLE
Tradução para inglês

### ISSUE THREAD

**Issue by rene-kt** [mathh95/css4noobs#39]
O que acha de disponibilizar uma tradução de todos os arquivos md para inglês? vai abranger o conteúdo, abrir para mais PR (adicionando links e novos conteúdos em inglês)  e com certeza vai atingir ainda mais pessoas.  Dependendo do feedback, eu mesmo faço a tradução e abro um PR.

**Comment by mathh95** [comment]
fica a vontade mano, repositorio ta ai pra isso
