### ISSUE TITLE
Conteúdo do CSS4Noobs

### ISSUE THREAD

**Issue by gitlherme** [mathh95/css4noobs#8]
Opa!

Passando pra deixar uma possível grade pro css4noobs!

# Guia básico para iniciantes em CSS

- O que é CSS;
- Como o CSS funciona;
- Quais suas vantagens;
- Adicionando CSS no nosso HTML;
- Modulo I - Básico
  - Box Model;
  - Background;
  - Border;
  - Table;
  - Lists;
  - Color;
  - Font;
  - Display;
  - Position;
  - Links;
  - Text (text-align, letter-spacing, etc);
  - Z-index;
  - Units (px, em, rem, %);
  - Transition;

---

- Módulo II - Intermediário
  - Pseudo-classes;
  - Pseudo-seletores;
  - Flexbox;
  - CSS Grid;
  - Animation;

---

## Referências

[https://cdn.rawgit.com/hostinger/banners/94941d64/tutorials/pdf/CSS-3-Cheatsheet.pdf](https://cdn.rawgit.com/hostinger/banners/94941d64/tutorials/pdf/CSS-3-Cheatsheet.pdf)
[https://www.hostinger.com.br/tutoriais/o-que-e-css-guia-basico-de-css/](https://www.hostinger.com.br/tutoriais/o-que-e-css-guia-basico-de-css/)

---

O que acham? 

E quais as possíveis adições pros módulos intermediário e avançado?

Acham que algo deve ser reorganizado?

Abraços,
gitlherme

**Comment by mathh95** [comment]
Pra mim ta muito bom, só acho que o text e o font poderiam entrar numa categoria de manipulaçao de texto. Eu já tava montando uma parte de manipulação de texto com font e text praticamente.

**Comment by gitlherme** [comment]
Show demais, mano!

**Comment by jaocarli** [comment]
Rapaz do céu, tá brabíssimo!

**Comment by gitlherme** [comment]
Vou atualizar o README com essas informações hoje e vamos criando os conteúdos em cima disso, que tal?

**Comment by mathh95** [comment]
Pra mim, perfeito. Vamo que vamo!

**Comment by gitlherme** [comment]
Fechando a issue por enquanto, caso seja necessário, abrimos denovo =)
